### PR TITLE
Change RFC6979 implementation to be a generic PRNG

### PR DESCRIPTION
**Pull request by sipa**
Instead of making it take key, message, and extra data separate, just pass in a byte array of seed data, turning it into just a non-EC specific PRNG.

The usage inside the blinding code and the tests is also adapted to make use of this in a more natural way.

### CODE REVIEW

**Comment by sipa** [comment]
@gmaxwell Want to review?

**Comment by dcousens** [comment]
@sipa maybe its taken care by `secp256k1_rfc6979_hmac_sha256_initialize`,  but `RFC6979` specifies that you

> repeat until T is within the interval [1, n - 1] and is suitable for ECDSA

Where suitable for `ECDSA` means the `r` and `s` values are not `=== 0`.
Is this handled externally as part of the libraries signing process?
In which case, I assume you feed `T` back in as the seed or?

**Comment by sipa** [comment]
@dcousens Right, secp256k1_rfc6979_hmac_sha256 only implements the PRNG side of the construction. The specific use as defined by RFC6979 is done inside the signing code.

**Comment by apoelstra** [comment]
With benchmarks on
```
src/bench_internal.c: In function ‘bench_rfc6979_hmac_sha256’:
src/bench_internal.c:268:9: error: too many arguments to function ‘secp256k1_rfc6979_hmac_sha256_initialize’
         secp256k1_rfc6979_hmac_sha256_initialize(&rng, data->data, 32, data->data, 32, NULL, 0);
         ^
In file included from src/bench_internal.c:11:0:
src/hash_impl.h:205:13: note: declared here
 static void secp256k1_rfc6979_hmac_sha256_initialize(secp256k1_rfc6979_hmac_sha256_t *rng, const unsigned char *key, size_t keylen) {
             ^
make: *** [src/bench_internal-bench_internal.o] Error 1
```

**Comment by sipa** [comment]
Rebased and fixed bug found by @apoelstra.

**Comment by gmaxwell** [comment]
ACK. (but see nit)

**Comment by apoelstra** [comment]
tested ACK

**Comment by sipa** [comment]
Addressed nit.

**Pull request merged**
