### PR TITLE
Portability fixups

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by sipa** [comment]
@luke-jr Is this still needed?

**Comment by luke-jr** [comment]
Looks like just the pkg-config stuff is useful now. Rebased

**Comment by sipa** [comment]
@theuni Can you have a look?

**Comment by theuni** [comment]
@luke-jr If we're going to fall back to AC_CHECK_HEADER/AC_CHECK_LIB after the pkg-config check for openssl has failed, we'll need to do a TRY_LINK on it before trusting it. Otherwise, a system lib could be found on a cross build where no pkg-config'd openssl exists, and the final link would fail.

Now that I think about it though, may as well just do a TRY_LINK after pkg-config _and_ the fallback, since pkg-config could feasibly find a system lib as well.

Other than that, looks good.

**Comment by sipa** [comment]
@luke-jr care to have a look at @theuni's suggestion?

**Comment by luke-jr** [comment]
If AC_* ever pick up the wrong library, that seems a bug in autotools?

**Comment by theuni** [comment]
Yea, never mind that suggestion. Lgtm.

**Pull request merged**
