### PR TITLE
Add ability to pass extra entropy to rfc6979

### PR DESCRIPTION
**Pull request by sipa**
Suggested by Greg Maxwell.

### CODE REVIEW

**Comment by gmaxwell** [comment]
I've sent email to Trevor Perrin on the question of exactly how the 3.6 "additional data" was supposed to be applied with respect to steps 3.2.d vs 3.2.f in the draft.

I believe all solutions are likely to be adequate but for consistency I thought it would be good to clarify whats intended in the draft.

**Comment by sipa** [comment]
Updated to apply it both 3.2.d and 3.2.f.

**Comment by gmaxwell** [comment]
ACK with https://people.xiph.org/~greg/0001-Add-a-simple-testcase-for-signing-with-rfc6979-extra.patch  or something substantially similar added. :)

**Comment by sipa** [comment]
Included your commit.

**Comment by sipa** [comment]
ACK extra commit.

**Pull request merged**
