### PR TITLE
bugfix: don't blow up on "ARG_CHECK(ctx != NULL)"

### PR DESCRIPTION
**Pull request by theuni**
The obvious fix for #300. I'm not sure if this should be handled in the same macro though.

### CODE REVIEW

**Comment by apoelstra** [comment]
I think a better fix is to replace the affected `ARG_CHECK`s with `VERIFY_CHECK`. Or even to put a `VERIFY_CHECK` for `ctx != NULL` in the `ARG_CHECK` macro itself.

I think we'll get burned if we don't terminate the program on null context, since it's used inside of so many macros.

**Comment by sipa** [comment]
Agree with @apoelstra. This will just make the accidental passing of
ctx==NULL harder to discover.

**Comment by theuni** [comment]
Ok, fine by me. This was just the "fix it as it lies" change. I'd much prefer to handle the ctx logic separately from the other args.

**Comment by apoelstra** [comment]
Can you replace this with a patch that replaces any `ARG_CHECK`s on `ctx` with `VERIFY_CHECK`? (If not I can do it.)

**Comment by theuni** [comment]
Updated as suggested. Also moved one case where the context was checked after other arguments.

**Comment by theuni** [comment]
Updated again. I accidentally left the original change to the ARG_CHECK macro in, gone now.

**Pull request merged**
