### PR TITLE
[API BREAK] Introduce explicit contexts

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by DavidEGrayson** [comment]
Looks good.  I would be tempted to remove the "flags" argument from secp256k1_context_create and just let people use the other functions, since it makes the API surface smaller.

**Comment by gmaxwell** [comment]
Need to worry about some combinatorial blowup, e.g. with each mixture of starting options having a new entry point. (We may have more options in the future)

**Comment by sipa** [comment]
@gmaxwell I'm not sure whether you're in favor or against the flags argument...

**Comment by gmaxwell** [comment]
For flags. Because if you have six flags or wahtever you might need 2^6 (or more) entriy points otherwise)

**Comment by DavidEGrayson** [comment]
You just need one `secp256k1_context_initialize_*` entry point for each high-level feature, because multiple initialization functions can be called on the same context after it is created.  So it's O(N), not O(2^N).

**Comment by gmaxwell** [comment]
Hm.  Doesn't address the case where it's cheaper to initilize a&&b than a, b  or where  b means you throw out what A does, without having a weird interface where some interact and some don't and some are slower unless you combine them.

**Comment by DavidEGrayson** [comment]
Yeah, that's true, so that would be a reason to be a good reason to keep the `flags` argument around.

**Comment by DavidEGrayson** [comment]
I think the API for creation/initialization could be simplified to just two functions:

```c
secp256k1_context_t* secp256k1_context_create();
void secp256k1_context_initialize(secp256k1_context_t* ctx, int flags); // can call multiple times
```

This allows special optimizations of the initialization process, regardless of when the initialization is performed, without combinatorial blowup of entry points.  It makes the API simpler because there would be fewer functions and only one way to initialize a context.  (Sorry if I'm missing something and this is just another lame idea for some reason!)

**Comment by sipa** [comment]
So there's a follow-up plan which is probably not obvious here, namely that some initializations may gain parameters (specifically: the size of the tables), which you probably can't encode as just flags. The explicit initialization functions can then serve as 'advanced' versions, while the flagged create_context does defaulty things.

**Comment by sipa** [comment]
Rebased.

**Comment by sipa** [comment]
And rebased again.

**Comment by sipa** [comment]
And again.

@gmaxwell I think we'll see significant API changes still soon (especially if we'd incorporate #179 and similar things). The bulk of this PR is introducing the contexts, and is a bit of a pain to maintain. How to actually build the contexts can be changed later, I think.

**Comment by sipa** [comment]
Removed the per-feature initialization functions for now.

**Comment by sipa** [comment]
Rebased.

**Comment by sipa** [comment]
@gmaxwell Review plz? *puppy eyes*

**Comment by gmaxwell** [comment]
Okay, I think I've run out of nits.

**Comment by sipa** [comment]
Nits addressed.

**Comment by gmaxwell** [comment]
Would be nice to brace that IF; either way:  ACK.

**Pull request merged**
