### PR TITLE
Avoid some implicit type conversions to make C++ compilers happy.

### PR DESCRIPTION
**Pull request by gmaxwell**

### CODE REVIEW

**Comment by dcousens** [comment]
@gmaxwell any reason for C style casts?

**Comment by dcousens** [comment]
@gmaxwell any reason for C style casts?

**Comment by gmaxwell** [comment]
@dcousens Because this software is written in strict C89 (plus a couple of narrow additions like long long).

The reason for this change is that someone may still compile it with a C++ compiler because that is all they have available or some other reason (e.g. they have some analysis or instrumentation code that is C++ only), and there is no reason to be gratuitously incompatible.

**Comment by dcousens** [comment]
@gmaxwell ah!  Sorry, I completely forgot about that,  just context switched and read C++ in the title.  Cheers for clearing that up :)

**Pull request merged**
