### PR TITLE
Fix compilation with C++

### PR DESCRIPTION
**Pull request by vinniefalco**
This is needed to compile the library as C++

### CODE REVIEW

**Comment by apoelstra** [comment]
How do you compile as C++? Is this something we can get Travis to do?

**Comment by sipa** [comment]
Judging by earlier comments by Vinnie, I assume he is directly #include'ing
the .c source inside another project's C++ source code.

**Comment by vinniefalco** [comment]
@sipa Right

**Comment by apoelstra** [comment]
ACK

**Comment by gmaxwell** [comment]
For testing you can override CC=g++   and bypass the compile test in configure.   I don't have a way to do the test without patching right now but perhaps its possible. A CI build that does this would be nice, otherwise it'll just be periodic fixes.

**Pull request merged**
