### PR TITLE
Use faster byteswapping and avoid alignment-increasing casts

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
9% faster SHA256 and RFC6979.

**Comment by gmaxwell** [comment]
ACK.  (remind me to test on BE if I forget to remove this request.)

**Comment by sipa** [comment]
clang seems to warn about changed alignment when casting. I don't see why that is a problem, so perhaps we should try to avoid that warning?

**Comment by sipa** [comment]
@theuni opinion?

**Comment by theuni** [comment]
@sipa I took a quick stab at avoiding changing alignment requirements: https://github.com/theuni/secp256k1/commit/78df7673f9d31627ae6425face109a0df6ac08ac just to see how much trouble it'd be. Assuming I didn't muck it up too badly, overhead seems minimal. It's hard to imagine this causing any real issues, though.

**Comment by sipa** [comment]
Hmm, a 1% slowdown. This shouldn't be necessary at all...

**Comment by sipa** [comment]
I've rewritten this based on @theuni's suggestion, taking it a step further. Oddly enough, it's even faster than the previous version.

Also, I've just switched to a different byteswapping macro, which recent GCC at -O2 and above automatically convert to a bswap instruction.

**Comment by sipa** [comment]
@theuni clang-3.5 also optimizes the construct to a bswap; I haven't tried any other implementation.

**Comment by sipa** [comment]
10.5% faster hashing now.

**Comment by theuni** [comment]
Nice! Tested ACK. Roughly an 8% speedup here from a very quick test.

**Pull request merged**
