### PR TITLE
API cleanups

### PR DESCRIPTION
**Pull request by luke-jr**
One more potential change missing:
* secp256k1_ecdsa_signature_parse_der: BER violations are supported, but how do we enforce BIP66? could reserialised and memcmp, but maybe it'd be more optimal to have a flag?

### CODE REVIEW

**Comment by sipa** [comment]
Needs rebase.

**Comment by luke-jr** [comment]
Merge-rebased. Is that okay?

**Comment by sipa** [comment]
@luke-jr Please actually rebase :)

**Comment by luke-jr** [comment]
Aww, okay. :(

Done.

**Comment by sipa** [comment]
ACK

**Pull request merged**
