### PR TITLE
This community NEEDS to adopt a code of conduct. Recent events make t…

### PR DESCRIPTION
**Pull request by jrmithdobbs**
…his glaringly obvious.

### CODE REVIEW

**Comment by jrmithdobbs** [comment]
Let me know if you'd like me to squash.

**Comment by jrmithdobbs** [comment]
I want to be clear here. I am a staunch supporter of free speech and have previously been opposed to such things. My mind has been changed, not just by this project, by watching friends and talented engineers berated, harassed, and generally have their mental health destroyed.

**Comment by jrmithdobbs** [comment]
I'm unsure as to whether the current contact language is appropriate as I agree with said policy that anonymity preservation should be an option when reporting.

Input?

**Comment by yamamushi** [comment]
Who is going to be responsible for governing this policy? 

Will this open us up to the possibility of having a  "man in the high castle" scenario, where one person dictates what is offensive based on their own personal feelings? 

Also, if that happens, will there be any arbitration procedures for those falsely accused of harassment, or perhaps even those who were just taken the wrong way when putting forth their thoughts on any given topic? 

I guess what I'm trying to say is, who will watch the watchers?

**Comment by jrmithdobbs** [comment]
I leave those questions to the maintainers themselves. This is becoming a widely accepted policy amongst respectable open source projects and I'm tiring of watching the decline of this one.

**Comment by jrmithdobbs** [comment]
This one being "bitcoin software in general," to be clear, I'm making no accusations and @sipa is a very congenial and helpful person in specific.

**Comment by jrmithdobbs** [comment]
You know I had cc'ed the author of that clause on twitter before saying anything about zeromq here, yes?

You explicitly state you will discriminate against anyone you want and *I'm* the bad actor?

Classy.

**Comment by yamamushi** [comment]
You already tried pulling this nonsense into libbitcoin, https://github.com/libbitcoin/libbitcoin/pull/355 , which was wholly rejected there. 

It seems to me that you are trying to address a problem that doesn't exist.

**Comment by unclediazepam** [comment]
Funny how often the ones pushing for these codes of conduct are guilty of the poor behavior they wish to punish others for:

https://storify.com/willrad/breaking-linux-user-is-kind-of-an-asshole

@jrmithdobbs is described here as a "loudmouthed jerk with enormous demands and nothing to contribute but noise"

I would say that's stunningly accurate.

**Comment by apoelstra** [comment]
I haven't yet read this, but if the goal here is to have a CoC for libsecp256k1, I think the PR should say that (rather than "this project"). If you mean the Bitcoin community in general should be less toxic, sure, but I don't think this project is the place to start that.

In general, interactions within libsecp256k1 seem to me to be polite and technical. This is maybe the nicest place you can find within the Bitcoin community.

So while I might sign onto a CoC (though again, I haven't yet taken the time to read this one) I'm unsure one is really needed in this case.

Having said all this, please do not turn this PR, or any PR, into a personal fight. @jrmithdobbs's conduct here or elsewhere is not relevant in my mind to the merits of this pull request.

**Comment by jrmithdobbs** [comment]
They do indeed and again I do not wish to imply otherwise. It is my feeling that declaring these things up front to explicitly state intent is more welcoming. That is all there is to this. Hats off to you guys, you do fantastic work.

**Comment by jrmithdobbs** [comment]
*indeed seem to be congenial I meant. That is why I specifically called out @sipa's awesomeness as an example when I really I had stated that poorly.

**Comment by unclediazepam** [comment]
@apoelstra I appreciate you trying to be equanimous on this subject, however, it is precisely "conduct here or elsewhere" that this PR concerns:

From the PR:

> This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community.

This type of verbiage can (and has) been used in the past to persecute those for their personal views even when expressed completely separate from the context of the open source project adopting the CoC.

These CoCs are an attempt by professional activists (not project committers) to push authoritarian social politics into open source communities where they do not belong.

The CoC is not needed and should be viewed for what it is: an outsider attempting to disrupt and push their political agenda with no concern for how their actions negatively effect or polarize the open source project.

**Comment by apoelstra** [comment]
Thank you for your concern @unclediazepam. I have seen this happen in other projects, and I do consider this risk quite serious, as well as the risk that we develop or invite a "language police" culture.

As I mentioned in my earlier post, I believe that the people working on libsecp256k1 already provide a welcoming and polite environment, though I'm willing to be convinced otherwise. In particular, I think the contributors here who have **not** suffered adverse mental health effects from the caustic environment in the wider Bitcoin community (aside from those who ignore it entirely) are a minority. So I trust the current maintainers to uphold the current level of conduct, if only for their own sake.

So with those thoughts I'm going to leave this PR alone for a while, and perhaps a maintainer with a more strongly-felt stance will step in.

**Comment by jrmithdobbs** [comment]
I just want to link this here: https://github.com/bitcoin/bitcoin/pull/7243#issuecomment-166467231

**Comment by sipa** [comment]
Thanks for your kind words, but we'll deal with this problem when it appears.

**Pull request closed without merging**
