### PR TITLE
Benchmarks for all internal operations

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by gmaxwell** [comment]
Needs some endomorphism ifdefs.

**Comment by gmaxwell** [comment]
The switching between ns and microseconds is potentially confusing. Maybe always print ns?  (e.g. makes it more complicated to make dumb graphing scripts, or a risk that you'll misread something)

**Comment by gmaxwell** [comment]
secp256k1_ecmult_wnaf ?

**Comment by gmaxwell** [comment]
secp256k1_ecmult_wnaf ?

**Comment by sipa** [comment]
Updated. Everything is printed in us, in decimal notation, with at least 3 significant digits. Also, added a field_sqr and ecmult_wnaf benchmark.

**Comment by gmaxwell** [comment]
ACK.

**Pull request merged**
