### PR TITLE
[API BREAK] Explicit flag handling (rebase + modification of #324)

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by sipa** [comment]
This is an update of #324 with the following changes:
* Keep the lower 8 bits of flags to indicate their type
* Revert the change to pass-through the compression flag to the eckey module (which was a layer violation, the flag was defined at a higher level but used on a lower one).

**Comment by sipa** [comment]
Comments, @rustyrussell @luke-jr ?

**Comment by luke-jr** [comment]
I do not understand the *reason* for pulling flags out of src/eckey_impl.h.

Besides that, fully-reviewed-and-seems-good ACK.

**Comment by sipa** [comment]
Luke: the lower-level eckey code should not depend on the top-level wrapper
whose interface is exposed.

**Comment by sipa** [comment]
Rebased, and renamed unsigned int to int for bool flag.

**Comment by sipa** [comment]
Rebased on top of #340.

**Pull request merged**
